spring:
  application:
    name: onedayboot
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/onedayboot
    driver-class-name: org.h2.Driver
    username: sa
    password:
logging:
  level:
    org:
      springframework: INFO
    com:
      oneday: INFO
    hibernate: WARN
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
